version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: pip-tools
    versions:
    - 5.5.0
    - 6.0.0
    - 6.0.1
  - dependency-name: pycryptodome
    versions:
    - 3.10.1
  - dependency-name: jinja2
    versions:
    - 2.11.3
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: mako
    versions:
    - 1.1.4
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
